version: '3.9'

services:
  app01: &app01
    build:
      dockerfile: app.Dockerfile
      context: .
    hostname: app01
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/rinha2024?pool=30&encoding=utf-8"
    volumes:
      - .:/rinha
    networks:
      - rinha-network
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  app02:
    <<: *app01
    hostname: app02

  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha2024
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - rinha-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "300MB"

  nginx:
    image: nginx:1.25
    ports:
      - 9999:9999
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-network
    depends_on:
      - app01
      - app02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  rinha-network:
    driver: bridge
